from . import base
from . import facebook_mixin
from . import mail_channel
from . import note
from . import omi_fb_access_token
from . import omi_fb_permission
from . import res_config_settings
from . import res_users
from . import sale_order
