from . import base
from . import facebook_mixin
from . import mail_channel
from . import note
from . import omi_fb_page
from . import omi_fb_permission
from . import omi_quick_reply
from . import res_config_settings
from . import res_partner
from . import sale_order
